Controllers films users
bad-decision/java-filmorate pull request #1
Opened 2022-08-08 20:39 UTC by bad-decision

- Реализованы два контроллера
- Валидация реализована при помощи аннотаций
- Реализована кастомная аннотация на дату релиза фильма
- На кастомную аннотацию написаны junit тесты
- Пройдены postman тесты

2022-08-09 20:29 UTC, sergeymamonov requested changes

2022-08-09 20:29 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmValidationTest.java
> +    private Film getCorrectFilm() {
Можно воспользоваться аннотацией @BeforeEach

2022-08-10 17:56 UTC, bad-decision commented on src/test/java/ru/yandex/practicum/filmorate/FilmValidationTest.java
> +    private Film getCorrectFilm() {
Воспользовался)

2022-08-11 04:09 UTC, sergeymamonov approved these changes

2022-08-19 07:31 UTC, merged