feat: добавить логику в контроллеры
bad-decision/java-filmorate pull request #2
Opened 2022-08-19 21:12 UTC by bad-decision

2022-08-19 21:15 UTC, bad-decision commented
- Добавлена логика в контроллеры
- Пройдены тесты
- Сделан рефакторинг пакетов
- Добавлен swagger и mapStruct

2022-08-21 15:39 UTC, sergeymamonov requested changes

2022-08-21 15:39 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.add(film);
Лучше делать проверки в коде. Например, что в методе получаем не null на входе, если грозит NPE. Что фильма с таким id уже нет в мапе, иначе перезатрем, это опасно.

Поэтому посмотрите, где лучше по коду добавить такие проверки.

2022-08-22 11:50 UTC, bad-decision commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.add(film);
Добавил проверки в сервисах на NPE для входных параметров. Не совсем понял пример с перезатиранием фильма в мапе. В update и delete проводится проверка, что элемент существует. В create не особо важно с каким id он пришёл, storage (автоинкремент в бд) выдаст новый id.

2022-08-22 12:44 UTC, bad-decision commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.add(film);
Добавил разбивку по пакетам. 
Сделал логирование и валидацию только на английском.
Добавил базовый сервис. 
Необходимость и важность базового контроллера не особо прочувствовал.

2022-08-22 20:07 UTC, sergeymamonov approved these changes

2022-08-22 20:07 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/web/converter/FilmToFilmResponseDTO.java
> +    public FilmResponseDto convert(Film film) {
Не очень понимаю, а зачем написан этот класс руками, а не с помощью MapStruct?

2022-09-10 17:47 UTC, merged