Add database
bad-decision/java-filmorate pull request #3
Opened 2022-09-14 14:27 UTC by bad-decision

2022-09-15 15:54 UTC, sergeymamonov requested changes
Практика делать в цикле запросы в БД - это плохая практика. Нужно стараться, чтобы запрос в БД был один. Постарайтесь переделать, посмотрите, как можно записывать в БД массивы.

2022-09-15 15:54 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    name varchar
Лучше ограничить длину поля определенным количеством символов. Ниже аналогично.

2022-09-15 15:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/FilmController.java
>      public FilmResponseDto getById(@PathVariable Long id) {
Я бы назвал класс не FilmResponseDto, а FilmRestView. То есть контроллер возвращает представление.

2022-09-15 15:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/FilmController.java
>      public FilmResponseDto update(@Valid @RequestBody FilmRequestDto filmDto) {
Я бы назвал класс не FilmRequestDto, а FilmRestCommand. То есть мы получаем объект, который потом конвертанем и запишем в хранилище.

2022-09-16 08:49 UTC, bad-decision commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/FilmController.java
>      public FilmResponseDto getById(@PathVariable Long id) {
Переименовал конечно, но для меня View это отсылка к архитектуре MVC.

2022-09-16 08:50 UTC, bad-decision commented on src/main/resources/schema.sql
> +    name varchar
Длину ограничил. Цикл переделал при помощи batch запроса.

2022-09-16 13:42 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/web/controller/FilmController.java
>      public FilmResponseDto getById(@PathVariable Long id) {
да, все что возвращается клиенту, пользователю можно назвать View.

2022-09-16 13:55 UTC, sergeymamonov approved these changes

2022-09-16 17:52 UTC, merged